// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Whether the user has let the app read their Wallet.
enum WalletAuthorization {
  notDetermined,
  denied,
  authorized,
}

/// What the account is, in the app's own words rather than FinanceKit's. Nothing emits `savings`
/// yet: FinanceKit does not say which asset accounts are savings, and guessing from the name is
/// how you end up deleting someone's data over a rename.
enum WalletAccountKind {
  creditCard,
  cash,
  savings,
}

/// Which way money moved. The server puts the sign on, so nothing here is ever negative.
enum WalletCreditDebit {
  credit,
  debit,
}

class WalletAccount {
  WalletAccount({
    required this.externalId,
    required this.name,
    required this.kind,
    required this.balance,
    required this.creditDebit,
  });

  String externalId;

  String name;

  WalletAccountKind kind;

  /// Unsigned, as a decimal string. Doubles do not hold money.
  String balance;

  WalletCreditDebit creditDebit;

  List<Object?> _toList() {
    return <Object?>[
      externalId,
      name,
      kind,
      balance,
      creditDebit,
    ];
  }

  Object encode() {
    return _toList();  }

  static WalletAccount decode(Object result) {
    result as List<Object?>;
    return WalletAccount(
      externalId: result[0]! as String,
      name: result[1]! as String,
      kind: result[2]! as WalletAccountKind,
      balance: result[3]! as String,
      creditDebit: result[4]! as WalletCreditDebit,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WalletAccount || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(externalId, other.externalId) && _deepEquals(name, other.name) && _deepEquals(kind, other.kind) && _deepEquals(balance, other.balance) && _deepEquals(creditDebit, other.creditDebit);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class WalletCharge {
  WalletCharge({
    required this.accountExternalId,
    required this.externalId,
    required this.amount,
    required this.creditDebit,
    required this.date,
    required this.name,
    required this.pending,
  });

  String accountExternalId;

  String externalId;

  /// Unsigned, as a decimal string.
  String amount;

  WalletCreditDebit creditDebit;

  /// `yyyy-MM-dd`.
  String date;

  String name;

  bool pending;

  List<Object?> _toList() {
    return <Object?>[
      accountExternalId,
      externalId,
      amount,
      creditDebit,
      date,
      name,
      pending,
    ];
  }

  Object encode() {
    return _toList();  }

  static WalletCharge decode(Object result) {
    result as List<Object?>;
    return WalletCharge(
      accountExternalId: result[0]! as String,
      externalId: result[1]! as String,
      amount: result[2]! as String,
      creditDebit: result[3]! as WalletCreditDebit,
      date: result[4]! as String,
      name: result[5]! as String,
      pending: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WalletCharge || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accountExternalId, other.accountExternalId) && _deepEquals(externalId, other.externalId) && _deepEquals(amount, other.amount) && _deepEquals(creditDebit, other.creditDebit) && _deepEquals(date, other.date) && _deepEquals(name, other.name) && _deepEquals(pending, other.pending);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// One read of Wallet.
class WalletChanges {
  WalletChanges({
    required this.accounts,
    required this.inserted,
    required this.updated,
    required this.deleted,
    required this.historyToken,
  });

  List<WalletAccount> accounts;

  List<WalletCharge> inserted;

  List<WalletCharge> updated;

  /// External ids of charges that were reversed or declined.
  List<String> deleted;

  /// Where this read finished, to be sent back on the next one.
  String historyToken;

  List<Object?> _toList() {
    return <Object?>[
      accounts,
      inserted,
      updated,
      deleted,
      historyToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static WalletChanges decode(Object result) {
    result as List<Object?>;
    return WalletChanges(
      accounts: (result[0]! as List<Object?>).cast<WalletAccount>(),
      inserted: (result[1]! as List<Object?>).cast<WalletCharge>(),
      updated: (result[2]! as List<Object?>).cast<WalletCharge>(),
      deleted: (result[3]! as List<Object?>).cast<String>(),
      historyToken: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WalletChanges || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accounts, other.accounts) && _deepEquals(inserted, other.inserted) && _deepEquals(updated, other.updated) && _deepEquals(deleted, other.deleted) && _deepEquals(historyToken, other.historyToken);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WalletAuthorization) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WalletAccountKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is WalletCreditDebit) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is WalletAccount) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is WalletCharge) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is WalletChanges) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : WalletAuthorization.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : WalletAccountKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : WalletCreditDebit.values[value];
      case 132:
        return WalletAccount.decode(readValue(buffer)!);
      case 133:
        return WalletCharge.decode(readValue(buffer)!);
      case 134:
        return WalletChanges.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WalletApi {
  /// Constructor for [WalletApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WalletApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// False below iOS 17.4, outside the US, or wherever FinanceKit has no data to give.
  Future<bool> isAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.spendable.WalletApi.isAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<WalletAuthorization> authorizationStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.spendable.WalletApi.authorizationStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WalletAuthorization;
  }

  Future<WalletAuthorization> requestAuthorization() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.spendable.WalletApi.requestAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WalletAuthorization;
  }

  /// Everything since [historyToken], or everything Wallet holds when it is null. A token
  /// FinanceKit will not take is treated as null rather than as a failure, so a rejected token
  /// costs a backfill and nothing else.
  Future<WalletChanges> read(String? historyToken) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.spendable.WalletApi.read$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[historyToken]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WalletChanges;
  }
}
