// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsWallet(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashWallet(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsWallet(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsWallet(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsWallet(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsWallet(lhsKey, rhsKey) {
          if deepEqualsWallet(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsWallet(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashWallet(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashWallet(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashWallet(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashWallet(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashWallet(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashWallet(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Whether the user has let the app read their Wallet.
enum WalletAuthorization: Int {
  case notDetermined = 0
  case denied = 1
  case authorized = 2
}

/// What the account is, in the app's own words rather than FinanceKit's. Nothing emits `savings`
/// yet: FinanceKit does not say which asset accounts are savings, and guessing from the name is
/// how you end up deleting someone's data over a rename.
enum WalletAccountKind: Int {
  case creditCard = 0
  case cash = 1
  case savings = 2
}

/// Which way money moved. The server puts the sign on, so nothing here is ever negative.
enum WalletCreditDebit: Int {
  case credit = 0
  case debit = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct WalletAccount: Hashable {
  var externalId: String
  var name: String
  var kind: WalletAccountKind
  /// Unsigned, as a decimal string. Doubles do not hold money.
  var balance: String
  var creditDebit: WalletCreditDebit


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WalletAccount? {
    let externalId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let kind = pigeonVar_list[2] as! WalletAccountKind
    let balance = pigeonVar_list[3] as! String
    let creditDebit = pigeonVar_list[4] as! WalletCreditDebit

    return WalletAccount(
      externalId: externalId,
      name: name,
      kind: kind,
      balance: balance,
      creditDebit: creditDebit
    )
  }
  func toList() -> [Any?] {
    return [
      externalId,
      name,
      kind,
      balance,
      creditDebit,
    ]
  }
  static func == (lhs: WalletAccount, rhs: WalletAccount) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWallet(lhs.externalId, rhs.externalId) && deepEqualsWallet(lhs.name, rhs.name) && deepEqualsWallet(lhs.kind, rhs.kind) && deepEqualsWallet(lhs.balance, rhs.balance) && deepEqualsWallet(lhs.creditDebit, rhs.creditDebit)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WalletAccount")
    deepHashWallet(value: externalId, hasher: &hasher)
    deepHashWallet(value: name, hasher: &hasher)
    deepHashWallet(value: kind, hasher: &hasher)
    deepHashWallet(value: balance, hasher: &hasher)
    deepHashWallet(value: creditDebit, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WalletCharge: Hashable {
  var accountExternalId: String
  var externalId: String
  /// Unsigned, as a decimal string.
  var amount: String
  var creditDebit: WalletCreditDebit
  /// `yyyy-MM-dd`.
  var date: String
  var name: String
  var pending: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WalletCharge? {
    let accountExternalId = pigeonVar_list[0] as! String
    let externalId = pigeonVar_list[1] as! String
    let amount = pigeonVar_list[2] as! String
    let creditDebit = pigeonVar_list[3] as! WalletCreditDebit
    let date = pigeonVar_list[4] as! String
    let name = pigeonVar_list[5] as! String
    let pending = pigeonVar_list[6] as! Bool

    return WalletCharge(
      accountExternalId: accountExternalId,
      externalId: externalId,
      amount: amount,
      creditDebit: creditDebit,
      date: date,
      name: name,
      pending: pending
    )
  }
  func toList() -> [Any?] {
    return [
      accountExternalId,
      externalId,
      amount,
      creditDebit,
      date,
      name,
      pending,
    ]
  }
  static func == (lhs: WalletCharge, rhs: WalletCharge) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWallet(lhs.accountExternalId, rhs.accountExternalId) && deepEqualsWallet(lhs.externalId, rhs.externalId) && deepEqualsWallet(lhs.amount, rhs.amount) && deepEqualsWallet(lhs.creditDebit, rhs.creditDebit) && deepEqualsWallet(lhs.date, rhs.date) && deepEqualsWallet(lhs.name, rhs.name) && deepEqualsWallet(lhs.pending, rhs.pending)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WalletCharge")
    deepHashWallet(value: accountExternalId, hasher: &hasher)
    deepHashWallet(value: externalId, hasher: &hasher)
    deepHashWallet(value: amount, hasher: &hasher)
    deepHashWallet(value: creditDebit, hasher: &hasher)
    deepHashWallet(value: date, hasher: &hasher)
    deepHashWallet(value: name, hasher: &hasher)
    deepHashWallet(value: pending, hasher: &hasher)
  }
}

/// One read of Wallet.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WalletChanges: Hashable {
  var accounts: [WalletAccount]
  var inserted: [WalletCharge]
  var updated: [WalletCharge]
  /// External ids of charges that were reversed or declined.
  var deleted: [String]
  /// Where this read finished, to be sent back on the next one.
  var historyToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WalletChanges? {
    let accounts = pigeonVar_list[0] as! [WalletAccount]
    let inserted = pigeonVar_list[1] as! [WalletCharge]
    let updated = pigeonVar_list[2] as! [WalletCharge]
    let deleted = pigeonVar_list[3] as! [String]
    let historyToken = pigeonVar_list[4] as! String

    return WalletChanges(
      accounts: accounts,
      inserted: inserted,
      updated: updated,
      deleted: deleted,
      historyToken: historyToken
    )
  }
  func toList() -> [Any?] {
    return [
      accounts,
      inserted,
      updated,
      deleted,
      historyToken,
    ]
  }
  static func == (lhs: WalletChanges, rhs: WalletChanges) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsWallet(lhs.accounts, rhs.accounts) && deepEqualsWallet(lhs.inserted, rhs.inserted) && deepEqualsWallet(lhs.updated, rhs.updated) && deepEqualsWallet(lhs.deleted, rhs.deleted) && deepEqualsWallet(lhs.historyToken, rhs.historyToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WalletChanges")
    deepHashWallet(value: accounts, hasher: &hasher)
    deepHashWallet(value: inserted, hasher: &hasher)
    deepHashWallet(value: updated, hasher: &hasher)
    deepHashWallet(value: deleted, hasher: &hasher)
    deepHashWallet(value: historyToken, hasher: &hasher)
  }
}

private class WalletPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WalletAuthorization(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WalletAccountKind(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WalletCreditDebit(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return WalletAccount.fromList(self.readValue() as! [Any?])
    case 133:
      return WalletCharge.fromList(self.readValue() as! [Any?])
    case 134:
      return WalletChanges.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WalletPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WalletAuthorization {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WalletAccountKind {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? WalletCreditDebit {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? WalletAccount {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? WalletCharge {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? WalletChanges {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WalletPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WalletPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WalletPigeonCodecWriter(data: data)
  }
}

class WalletPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WalletPigeonCodec(readerWriter: WalletPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WalletApi {
  /// False below iOS 17.4, outside the US, or wherever FinanceKit has no data to give.
  func isAvailable() throws -> Bool
  func authorizationStatus(completion: @escaping (Result<WalletAuthorization, Error>) -> Void)
  func requestAuthorization(completion: @escaping (Result<WalletAuthorization, Error>) -> Void)
  /// Everything since [historyToken], or everything Wallet holds when it is null. A token
  /// FinanceKit will not take is treated as null rather than as a failure, so a rejected token
  /// costs a backfill and nothing else.
  func read(historyToken: String?, completion: @escaping (Result<WalletChanges, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WalletApiSetup {
  static var codec: FlutterStandardMessageCodec { WalletPigeonCodec.shared }
  /// Sets up an instance of `WalletApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WalletApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// False below iOS 17.4, outside the US, or wherever FinanceKit has no data to give.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spendable.WalletApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let authorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spendable.WalletApi.authorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizationStatusChannel.setMessageHandler { _, reply in
        api.authorizationStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizationStatusChannel.setMessageHandler(nil)
    }
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spendable.WalletApi.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { _, reply in
        api.requestAuthorization { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
    /// Everything since [historyToken], or everything Wallet holds when it is null. A token
    /// FinanceKit will not take is treated as null rather than as a failure, so a rejected token
    /// costs a backfill and nothing else.
    let readChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.spendable.WalletApi.read\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let historyTokenArg: String? = nilOrValue(args[0])
        api.read(historyToken: historyTokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readChannel.setMessageHandler(nil)
    }
  }
}
