platform :ios, '14.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Spendable' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Other native modules
  pod 'Plaid', '~> 1.1.37'

  # Automatically detect installed unimodules
  use_unimodules!
end
