// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGna1TwDY4tNJt4qJ01qZA5uy5NYjMpVk',
    appId: '1:973501356954:web:c28cd9ce3736fbf7b4f823',
    messagingSenderId: '973501356954',
    projectId: 'cloud-57',
    authDomain: 'cloud-57.firebaseapp.com',
    databaseURL: 'https://cloud-57.firebaseio.com',
    storageBucket: 'cloud-57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTkjIw6m4aoksPcLQ-9uBKwcOpUZ39pY8',
    appId: '1:973501356954:android:86e189505e5c889bb4f823',
    messagingSenderId: '973501356954',
    projectId: 'cloud-57',
    databaseURL: 'https://cloud-57.firebaseio.com',
    storageBucket: 'cloud-57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWecKWZ5z35TlE-Qq8ftDVqrFubrhXurg',
    appId: '1:973501356954:ios:881ed085cdbe2b46b4f823',
    messagingSenderId: '973501356954',
    projectId: 'cloud-57',
    databaseURL: 'https://cloud-57.firebaseio.com',
    storageBucket: 'cloud-57.appspot.com',
    iosClientId: '973501356954-lrbiflaqtjurtd6mjulgh0nhubn1ou00.apps.googleusercontent.com',
    iosBundleId: 'media.fiftyseven.spendable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWecKWZ5z35TlE-Qq8ftDVqrFubrhXurg',
    appId: '1:973501356954:ios:881ed085cdbe2b46b4f823',
    messagingSenderId: '973501356954',
    projectId: 'cloud-57',
    databaseURL: 'https://cloud-57.firebaseio.com',
    storageBucket: 'cloud-57.appspot.com',
    iosClientId: '973501356954-lrbiflaqtjurtd6mjulgh0nhubn1ou00.apps.googleusercontent.com',
    iosBundleId: 'media.fiftyseven.spendable',
  );
}
