defmodule Spendable.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      remove :goal

      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :name, :text
      modify :adjustment, :decimal
    end
  end

  def down do
    alter table(:budgets) do
      modify :adjustment, :goal
      modify :name, :string
      modify :inserted_at, :utc_datetime, default: nil
      modify :updated_at, :utc_datetime, default: nil

      add :goal, :decimal, default: 0.00
    end
  end
end
