defmodule Spendable.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      add :track_spending_only, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:budgets) do
      remove :track_spending_only
    end
  end
end