defmodule Spendable.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
    end
  end

  def down do
    alter table(:users) do
      modify :inserted_at, :utc_datetime_usec, default: nil
      modify :updated_at, :utc_datetime_usec, default: nil
    end
  end
end