defmodule Spendable.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:notification_settings, ["user_id"])

    alter table(:notification_settings) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :enabled, :boolean, null: false
    end

    execute(
      "ALTER INDEX notification_settings_user_id_device_token_index RENAME TO notification_settings_device_token_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX notification_settings_device_token_index RENAME TO notification_settings_user_id_device_token_index"
    )

    alter table(:notification_settings) do
      modify :enabled, :boolean, null: true
      modify :inserted_at, :utc_datetime, default: nil
      modify :updated_at, :utc_datetime, default: nil
    end

    drop_if_exists index(:notification_settings, ["user_id"],
                     name: "notification_settings_user_id_index"
                   )
  end
end
