defmodule Spendable.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      remove :category_id

      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :name, :text, null: false
      modify :amount, :decimal
    end
  end

  def down do
    alter table(:transactions) do
      modify :name, :string
      modify :inserted_at, :utc_datetime, default: nil
      modify :updated_at, :utc_datetime, default: nil

      add :category_id,
          references(:categories,
            column: :id,
            name: "transactions_category_id_fkey",
            type: :bigint
          ),
          null: false
    end
  end
end
