defmodule Spendable.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bank_accounts) do
      remove :available_balance

      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :type, :text
      modify :sub_type, :text
      modify :number, :text
      modify :name, :text
      modify :external_id, :text
      modify :balance, :decimal, null: false
    end

    create index(:bank_accounts, [:user_id], name: "bank_accounts_user_id_index")

    execute(
      "ALTER INDEX bank_accounts_user_id_external_id_index RENAME TO bank_accounts_external_id_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX bank_accounts_external_id_index RENAME TO bank_accounts_user_id_external_id_index"
    )

    drop index(:bank_accounts, [:user_id, name: "bank_accounts_user_id_index"])

    alter table(:bank_accounts) do
      modify :balance, :decimal, null: true
      modify :external_id, :string
      modify :name, :string
      modify :number, :string
      modify :sub_type, :string
      modify :type, :string
      modify :inserted_at, :utc_datetime, default: nil
      modify :updated_at, :utc_datetime, default: nil

      add :available_balance, :decimal, null: false
    end
  end
end
