defmodule Spendable.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :apple_identifier

      modify :firebase_id, :text, null: false
    end

    drop table(:categories)
    drop table(:transaction_tags)
    drop table(:tags)
  end

  def down do
    alter table(:users) do
      modify :firebase_id, :text, null: true

      add :apple_identifier, :string
    end
  end
end
