defmodule Spendable.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :budget_allocation_template_lines,
           "budget_allocation_template_lines_budget_allocation_template_id_fkey"
         )

    alter table(:budget_allocation_template_lines) do
      modify :budget_allocation_template_id,
             references(:budget_allocation_templates,
               column: :id,
               name: "budget_allocation_template_lines_budget_allocation_template_id_fkey",
               type: :bigint,
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(
           :budget_allocation_template_lines,
           "budget_allocation_template_lines_budget_allocation_template_id_fkey"
         )

    alter table(:budget_allocation_template_lines) do
      modify :budget_allocation_template_id,
             references(:budget_allocation_templates,
               column: :id,
               name: "budget_allocation_template_lines_budget_allocation_template_id_fkey",
               type: :bigint
             )
    end
  end
end
