defmodule Spendable.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      add :archived_at, :utc_datetime
    end
  end

  def down do
    alter table(:budgets) do
      remove :archived_at
    end
  end
end
