defmodule Spendable.Repo.Migrations.AddProviderToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :image, :text
      add :provider, :text, null: false, default: "firebase"
    end
  end

  def down do
    alter table(:users) do
      remove :provider
      remove :image
    end
  end
end
