defmodule Spendable.Repo.Migrations.BankMemberUuid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bank_accounts) do
      add :bank_member_uuid, :uuid
    end

    execute """
    UPDATE bank_accounts
    SET bank_member_uuid = bank_members.uuid
    FROM bank_members
    WHERE bank_accounts.bank_member_id = bank_members.id
    """

    alter table(:bank_accounts) do
      remove :bank_member_id
    end

    rename table(:bank_accounts), :bank_member_uuid, to: :bank_member_id

    alter table(:bank_members) do
      remove :id
      modify :uuid, :uuid, null: false, primary_key: true
    end

    rename table(:bank_members), :uuid, to: :id

    create index(:bank_members, ["user_id"])

    drop_if_exists unique_index(:bank_members, [:uuid], name: "bank_members_uuid_index")

    alter table(:bank_accounts) do
      modify :bank_member_id,
             references(:bank_members,
               column: :id,
               prefix: "public",
               name: "bank_accounts_bank_member_id_fkey",
               type: :uuid
             ),
             null: false
    end
  end

  def down do
    alter table(:bank_accounts) do
      modify :bank_member_id, :bigint
    end

    create unique_index(:bank_members, [:uuid], name: "bank_members_uuid_index")

    alter table(:bank_members) do
      modify :id, :bigint, default: nil
      # This is the `down` migration of the statement:
      #
      #     remove :uuid
      #

      # add :uuid, :uuid, default: fragment("uuid_generate_v4()")
    end

    drop_if_exists index(:bank_members, ["user_id"], name: "bank_members_user_id_index")
  end
end
