defmodule Spendable.Repo.Migrations.BankAccountUuid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bank_transactions) do
      add :bank_account_uuid, :uuid
    end

    execute """
    UPDATE bank_transactions
    SET bank_account_uuid = bank_accounts.uuid
    FROM bank_accounts
    WHERE bank_transactions.bank_account_id = bank_accounts.id
    """

    alter table(:bank_transactions) do
      remove :bank_account_id
    end

    rename table(:bank_transactions), :bank_account_uuid, to: :bank_account_id

    alter table(:bank_accounts) do
      remove :id
      modify :uuid, :uuid, null: false, primary_key: true
    end

    rename table(:bank_accounts), :uuid, to: :id

    create index(:bank_accounts, ["bank_member_id"])

    drop_if_exists unique_index(:bank_accounts, [:uuid], name: "bank_accounts_uuid_index")

    create unique_index(:bank_accounts, [:user_id, :external_id],
             name: "bank_accounts_external_id_index"
           )

    alter table(:bank_transactions) do
      modify :bank_account_id,
             references(:bank_accounts,
               column: :id,
               prefix: "public",
               name: "bank_transactions_bank_account_id_fkey",
               type: :uuid
             ),
             null: false
    end
  end

  def down do
    drop_if_exists unique_index(:bank_accounts, [:user_id, :external_id],
                     name: "bank_accounts_external_id_index"
                   )

    create unique_index(:bank_accounts, [:uuid], name: "bank_accounts_uuid_index")

    alter table(:bank_accounts) do
      modify :id, :bigint, default: nil
      # This is the `down` migration of the statement:
      #
      #     remove :uuid
      #

      # add :uuid, :uuid, default: fragment("uuid_generate_v4()")
    end

    drop_if_exists index(:bank_accounts, ["bank_member_id"],
                     name: "bank_accounts_bank_member_id_index"
                   )

    alter table(:bank_transactions) do
      modify :bank_account_id, :bigint
    end
  end
end
