defmodule Spendable.Repo.Migrations.BudgetUuidIsSet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budget_allocations) do
      remove :budget_id
    end

    drop constraint(:budget_allocations, "budget_allocations_budget_uuid_id_fkey")

    alter table(:budget_allocations) do
      modify :budget_uuid_id,
             references(:budgets,
               column: :uuid,
               name: "budget_allocations_budget_uuid_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    alter table(:budget_allocation_template_lines) do
      remove :budget_id
    end

    drop constraint(
           :budget_allocation_template_lines,
           "budget_allocation_template_lines_budget_uuid_id_fkey"
         )

    alter table(:budget_allocation_template_lines) do
      modify :budget_uuid_id,
             references(:budgets,
               column: :uuid,
               name: "budget_allocation_template_lines_budget_uuid_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    drop constraint("budgets", "budgets_pkey")

    alter table(:budgets) do
      modify :uuid, :uuid, null: false, primary_key: true

      remove :id
    end
  end

  def down do
    drop constraint("budgets", "budgets_pkey")

    create unique_index(:budgets, [:uuid], name: "budgets_uuid_index")

    alter table(:budgets) do
      # This is the `down` migration of the statement:
      #
      #     remove :id
      #

      # add :id, :bigserial, null: false, primary_key: true
      modify :uuid, :uuid, null: true, primary_key: false
    end

    drop constraint(
           :budget_allocation_template_lines,
           "budget_allocation_template_lines_budget_uuid_id_fkey"
         )

    alter table(:budget_allocation_template_lines) do
      modify :budget_uuid_id,
             references(:budgets,
               column: :uuid,
               name: "budget_allocation_template_lines_budget_uuid_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true
    end

    # alter table(:budget_allocation_template_lines) do
    # This is the `down` migration of the statement:
    #
    #     remove :budget_id
    #
    #
    # add :budget_id, references(:budgets, column: :id, name: "budget_allocation_template_lines_budget_id_fkey", type: :bigint, prefix: "public"), null: false
    # end
    #
    drop constraint(:budget_allocations, "budget_allocations_budget_uuid_id_fkey")

    alter table(:budget_allocations) do
      modify :budget_uuid_id,
             references(:budgets,
               column: :uuid,
               name: "budget_allocations_budget_uuid_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true
    end

    # alter table(:budget_allocations) do
    # This is the `down` migration of the statement:
    #
    #     remove :budget_id
    #
    #
    # add :budget_id, references(:budgets, column: :id, name: "budget_allocations_budget_id_fkey", type: :bigint, prefix: "public"), null: false
    # end
    #
  end
end
