defmodule Spendable.Repo.Migrations.BudgetArchive do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      modify :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:budgets) do
      modify :archived_at, :utc_datetime
    end
  end
end
