defmodule Spendable.Repo.Migrations.FinalUserUuid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :uuid, to: :id

    rename table(:transactions), :user_uuid, to: :user_id

    alter table(:transactions) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "transactions_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:budgets), :user_uuid, to: :user_id

    alter table(:budgets) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "budgets_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:budget_allocations), :user_uuid, to: :user_id

    alter table(:budget_allocations) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "budget_allocations_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:budget_allocation_templates), :user_uuid, to: :user_id

    alter table(:budget_allocation_templates) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "budget_allocation_templates_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:budget_allocation_template_lines), :user_uuid, to: :user_id

    alter table(:budget_allocation_template_lines) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "budget_allocation_template_lines_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:bank_transactions), :user_uuid, to: :user_id

    alter table(:bank_transactions) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "bank_transactions_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:bank_members), :user_uuid, to: :user_id

    alter table(:bank_members) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "bank_members_user_id_fkey",
               type: :uuid
             ),
             null: false
    end

    rename table(:bank_accounts), :user_uuid, to: :user_id

    alter table(:bank_accounts) do
      modify :user_id,
             references(:users,
               column: :id,
               prefix: "public",
               name: "bank_accounts_user_id_fkey",
               type: :uuid
             ),
             null: false
    end
  end

  def down do
    drop constraint(:bank_accounts, "bank_accounts_user_id_fkey")
    rename table(:bank_accounts), :user_id, to: :user_uuid

    drop constraint(:bank_members, "bank_members_user_id_fkey")
    rename table(:bank_members), :user_id, to: :user_uuid

    drop constraint(:bank_transactions, "bank_transactions_user_id_fkey")
    rename table(:bank_transactions), :user_id, to: :user_uuid

    drop constraint(
           :budget_allocation_template_lines,
           "budget_allocation_template_lines_user_id_fkey"
         )

    rename table(:budget_allocation_template_lines), :user_id, to: :user_uuid

    drop constraint(:budget_allocation_templates, "budget_allocation_templates_user_id_fkey")
    rename table(:budget_allocation_templates), :user_id, to: :user_uuid

    drop constraint(:budget_allocations, "budget_allocations_user_id_fkey")
    rename table(:budget_allocations), :user_id, to: :user_uuid

    drop constraint(:budgets, "budgets_user_id_fkey")
    rename table(:budgets), :user_id, to: :user_uuid

    drop constraint(:transactions, "transactions_user_id_fkey")
    rename table(:transactions), :user_id, to: :user_uuid

    rename table(:users), :id, to: :uuid
  end
end
