defmodule Spendable.Repo.Migrations.BudgetUuidFinal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:budgets), :uuid, to: :id

    rename table(:budget_allocations), :budget_uuid_id, to: :budget_id

    rename table(:budget_allocation_template_lines), :budget_uuid_id, to: :budget_id

    drop_if_exists constraint(:budget_allocations, "budget_allocations_budget_uuid_id_fkey")

    drop_if_exists constraint(
                     :budget_allocation_template_lines,
                     "budget_allocation_template_lines_budget_uuid_id_fkey"
                   )

    drop_if_exists unique_index(:budgets, [:uuid], name: "budgets_uuid_index")

    alter table(:budget_allocations) do
      modify :budget_id,
             references(:budgets,
               column: :id,
               name: "budget_allocations_budget_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    alter table(:budget_allocation_template_lines) do
      modify :budget_id,
             references(:budgets,
               column: :id,
               name: "budget_allocation_template_lines_budget_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end
  end

  def down do
    rename table(:budget_allocation_template_lines), :budget_id, to: :budget_uuid_id

    rename table(:budget_allocations), :budget_id, to: :budget_uuid_id

    rename table(:budgets), :id, to: :uuid
  end
end
