defmodule Spendable.Repo.Migrations.AddUserUuid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE transactions
    SET user_uuid = users.uuid
    FROM users
    WHERE transactions.user_id = users.id
    """

    alter table(:budgets) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE budgets
    SET user_uuid = users.uuid
    FROM users
    WHERE budgets.user_id = users.id
    """

    alter table(:budget_allocations) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE budget_allocations
    SET user_uuid = users.uuid
    FROM users
    WHERE budget_allocations.user_id = users.id
    """

    alter table(:budget_allocation_templates) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE budget_allocation_templates
    SET user_uuid = users.uuid
    FROM users
    WHERE budget_allocation_templates.user_id = users.id
    """

    alter table(:budget_allocation_template_lines) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE budget_allocation_template_lines
    SET user_uuid = users.uuid
    FROM users
    WHERE budget_allocation_template_lines.user_id = users.id
    """

    alter table(:bank_transactions) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE bank_transactions
    SET user_uuid = users.uuid
    FROM users
    WHERE bank_transactions.user_id = users.id
    """

    alter table(:bank_members) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE bank_members
    SET user_uuid = users.uuid
    FROM users
    WHERE bank_members.user_id = users.id
    """

    alter table(:bank_accounts) do
      add :user_uuid, :uuid
    end

    execute """
    UPDATE bank_accounts
    SET user_uuid = users.uuid
    FROM users
    WHERE bank_accounts.user_id = users.id
    """
  end

  def down do
    alter table(:bank_accounts) do
      remove :user_uuid
    end

    alter table(:bank_members) do
      remove :user_uuid
    end

    alter table(:bank_transactions) do
      remove :user_uuid
    end

    alter table(:budget_allocation_template_lines) do
      remove :user_uuid
    end

    alter table(:budget_allocation_templates) do
      remove :user_uuid
    end

    alter table(:budget_allocations) do
      remove :user_uuid
    end

    alter table(:budgets) do
      remove :user_uuid
    end

    alter table(:transactions) do
      remove :user_uuid
    end
  end
end
