defmodule Spendable.Repo.Migrations.TransactionDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:budget_allocations, "budget_allocations_transaction_id_fkey")

    alter table(:budget_allocations) do
      modify :transaction_id,
             references(:transactions,
               column: :id,
               name: "budget_allocations_transaction_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:budget_allocations, "budget_allocations_transaction_id_fkey")

    alter table(:budget_allocations) do
      modify :transaction_id,
             references(:transactions,
               column: :id,
               name: "budget_allocations_transaction_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
