defmodule Spendable.Repo.Migrations.TemplateIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:budget_allocation_templates, ["user_id"])

    create index(:budget_allocation_template_lines, ["user_id"])

    create index(:budget_allocation_template_lines, ["budget_allocation_template_id"])

    create index(:budget_allocation_template_lines, ["budget_id"])
  end

  def down do
    drop_if_exists index(:budget_allocation_template_lines, ["budget_id"],
                     name: "budget_allocation_template_lines_budget_id_index"
                   )

    drop_if_exists index(:budget_allocation_template_lines, ["budget_allocation_template_id"],
                     name: "budget_allocation_template_lines_budget_allocation_template_id_index"
                   )

    drop_if_exists index(:budget_allocation_template_lines, ["user_id"],
                     name: "budget_allocation_template_lines_user_id_index"
                   )

    drop_if_exists index(:budget_allocation_templates, ["user_id"],
                     name: "budget_allocation_templates_user_id_index"
                   )
  end
end