defmodule Spendable.Repo.Migrations.CistringTransaction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :note, :citext
      modify :name, :citext
    end
  end

  def down do
    alter table(:transactions) do
      modify :name, :text
      modify :note, :text
    end
  end
end
