defmodule Spendable.Repo.Migrations.ChangeFirebaseIdToExternalId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :firebase_id, to: :external_id

    drop_if_exists unique_index(:users, [:firebase_id], name: "users_firebase_id_index")

    create unique_index(:users, [:external_id], name: "users_external_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:external_id], name: "users_external_id_index")

    create unique_index(:users, [:firebase_id], name: "users_firebase_id_index")

    rename table(:users), :external_id, to: :firebase_id
  end
end
