defmodule Spendable.Repo.Migrations.RemoveDefaultProvider do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :provider, :text, default: nil
    end
  end

  def down do
    alter table(:users) do
      modify :provider, :text, default: "firebase"
    end
  end
end
