defmodule Spendable.Repo.Migrations.TemplateUuid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budget_allocation_template_lines) do
      add :budget_allocation_template_uuid, :uuid
    end

    execute """
    UPDATE budget_allocation_template_lines
    SET budget_allocation_template_uuid = budget_allocation_templates.uuid
    FROM budget_allocation_templates
    WHERE budget_allocation_template_lines.budget_allocation_template_id = budget_allocation_templates.id
    """

    alter table(:budget_allocation_template_lines) do
      remove :budget_allocation_template_id
    end

    rename table(:budget_allocation_template_lines), :budget_allocation_template_uuid,
      to: :budget_allocation_template_id

    alter table(:budget_allocation_templates) do
      remove :id
      modify :uuid, :uuid, null: false, primary_key: true
    end

    rename table(:budget_allocation_templates), :uuid, to: :id

    alter table(:budget_allocation_template_lines) do
      modify :budget_allocation_template_id,
             references(:budget_allocation_templates,
               column: :id,
               prefix: "public",
               name: "budget_allocation_template_lines_budget_allocation_template_id_fkey",
               type: :uuid
             ),
             null: false
    end

    drop_if_exists unique_index(:budget_allocation_templates, [:uuid],
                     name: "budget_allocation_templates_uuid_index"
                   )
  end

  def down do
    alter table(:budget_allocation_template_lines) do
      modify :budget_allocation_template_id, :bigint
    end

    create unique_index(:budget_allocation_templates, [:uuid],
             where: "archived_at IS NULL",
             name: "budget_allocation_templates_uuid_index"
           )

    alter table(:budget_allocation_templates) do
      modify :id, :bigint, default: nil
      # This is the `down` migration of the statement:
      #
      #     remove :uuid
      #

      # add :uuid, :uuid, default: fragment("uuid_generate_v4()")
    end
  end
end
