defmodule Spendable.Repo.Migrations.BudgetAmount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      add :monthly_amount, :decimal
    end

    alter table(:bank_accounts) do
      modify :sync, :boolean, default: true
    end
  end

  def down do
    alter table(:bank_accounts) do
      modify :sync, :boolean, default: false
    end

    alter table(:budgets) do
      remove :monthly_amount
    end
  end
end
