defmodule Spendable.Repo.Migrations.BudgetedAmount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:budgets), :monthly_amount, to: :budgeted_amount

    alter table(:budgets) do
      modify :budgeted_amount, :decimal
    end
  end

  def down do
    alter table(:budgets) do
      modify :monthly_amount, :decimal
    end

    rename table(:budgets), :budgeted_amount, to: :monthly_amount
  end
end
