defmodule Spendable.Repo.Migrations.RemoveTrackSpendingOnly do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:budgets) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :track_spending_only
    # end
    # 
  end

  def down do
    # alter table(:budgets) do
    # This is the `down` migration of the statement:
    #
    #     remove :track_spending_only
    #
    # 
    # add :track_spending_only, :boolean, null: false, default: false
    # end
    # 
  end
end
