defmodule Spendable.Repo.Migrations.BankBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bank_accounts) do
      add :budget_id,
          references(:budgets,
            column: :id,
            name: "bank_accounts_budget_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bank_accounts, "bank_accounts_budget_id_fkey")

    alter table(:bank_accounts) do
      remove :budget_id
    end
  end
end
