#!/usr/bin/env bash
#
# Give this worktree its own database and Phoenix port so several worktrees run side by side.
#
# Every worktree shares the one postgres container: COMPOSE_PROJECT_NAME is pinned to "spendable"
# so `docker compose up -d db` reuses it, instead of each worktree starting its own and fighting
# over port 5432 (compose otherwise names the project after the directory). What is per-worktree is
# the database name and the port Phoenix binds.
#
#   slot 0 -> spendable_dev,      localhost:4000   (the primary checkout)
#   slot N -> spendable_dev_wtN,  localhost:4000 + N*100
#
# The assignment is written to a gitignored `.env.worktree`, which both mise (`[env] _.file`) and
# docker compose read, so `mix` and `docker compose` in this worktree pick it up automatically.
# Secrets stay in `.env` and are never touched.
#
# Usage:
#   scripts/setup-worktree.sh            # assign a slot, write .env.worktree, start postgres
#   scripts/setup-worktree.sh --no-up    # write .env.worktree only
#   scripts/setup-worktree.sh --force    # reassign a slot even if one is already recorded
set -euo pipefail

PORT_STEP=100
COMPOSE_PROJECT=spendable
START_DOCKER=1
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --no-up) START_DOCKER=0 ;;
    --force) FORCE=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# Root of *this* worktree, and the generated file we manage.
worktree_root="$(git rev-parse --show-toplevel)"
env_file="$worktree_root/.env.worktree"

# Slot 0 (the default database and port) belongs to the primary worktree - the first entry in
# `git worktree list`, i.e. the main checkout. It keeps the defaults even before it has an
# .env.worktree, so a running primary is never stomped on. Other worktrees allocate from 1 up.
primary_root="$(git worktree list --porcelain | sed -n 's/^worktree //p' | head -1)"
is_primary=0
[ "$worktree_root" = "$primary_root" ] && is_primary=1

# Collect the slots sibling worktrees already claimed (as a space-padded string, for bash 3.2)
# so the same slot is never handed out twice. Pre-claim slot 0 for the primary when we aren't it.
used_slots=" "
[ "$is_primary" -eq 0 ] && used_slots=" 0 "
existing_slot=""
while IFS= read -r line; do
  case "$line" in
    worktree\ *)
      wt_path="${line#worktree }"
      wt_env="$wt_path/.env.worktree"
      [ -f "$wt_env" ] || continue
      slot="$(grep -E '^WORKTREE_SLOT=' "$wt_env" 2>/dev/null | head -1 | cut -d= -f2 || true)"
      [ -n "$slot" ] || continue
      if [ "$wt_path" = "$worktree_root" ]; then
        existing_slot="$slot"
      else
        used_slots="${used_slots}${slot} "
      fi
      ;;
  esac
done < <(git worktree list --porcelain)

# Reuse our slot if we already have one (unless --force); otherwise take the lowest free one.
if [ "$is_primary" -eq 1 ]; then
  slot=0
elif [ -n "$existing_slot" ] && [ "$FORCE" -eq 0 ]; then
  slot="$existing_slot"
else
  slot=1
  while [ "${used_slots#* $slot }" != "$used_slots" ]; do
    slot=$((slot + 1))
  done
fi

port=$((4000 + slot * PORT_STEP))
if [ "$slot" -eq 0 ]; then
  suffix=""
else
  suffix="_wt${slot}"
fi

cat > "$env_file" <<EOF
# Generated by scripts/setup-worktree.sh - worktree slot ${slot}.
# A database name and port of this worktree's own, so worktrees run side by side on one postgres.
# This file reserves the slot; delete it and rerun the script to reassign. Secrets live in .env.
WORKTREE_SLOT=${slot}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT}
PORT=${port}
DB_NAME_SUFFIX=${suffix}
EOF

echo "Worktree slot ${slot}"
echo "  Phoenix     http://localhost:${port}"
echo "  Databases   spendable_dev${suffix} / spendable_test${suffix}"
echo "  wrote       ${env_file}"

# A fresh worktree has no .env, since it is gitignored and so never checked out. Seed it from the
# primary checkout so Google and Plaid credentials work here without hunting them down again.
if [ ! -f "$worktree_root/.env" ] && [ -f "$primary_root/.env" ]; then
  cp "$primary_root/.env" "$worktree_root/.env"
  echo "  copied      .env from ${primary_root}"
fi

if [ "$START_DOCKER" -eq 1 ]; then
  echo "Starting postgres (compose project ${COMPOSE_PROJECT})..."
  ( cd "$worktree_root" && COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT" docker compose up -d db )
  echo "Done. Next: mise exec -- mix setup && mise exec -- mix phx.server"
else
  echo "Skipped docker compose (--no-up). Start it with: docker compose up -d db"
fi
