name: Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3

      - uses: jdx/mise-action@v2

      - name: Cache Deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile --warnings-as-errors, ecto.reset
      - run: mix coveralls.json

      # - name: Check Code Coverage
      #   uses: coverbot-io/coverbot-action@v1
      #   with:
      #     file: cover/excoveralls.json
      #     coverbot_api_key: ${{ secrets.COVERBOT_API_KEY}}
      #     github_token: ${{ secrets.GITHUB_TOKEN}}

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: jdx/mise-action@v2

      - name: Cache Deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile
      - run: mix format --check-formatted

  credo:
    name: Credo
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - uses: jdx/mise-action@v2

      - name: Cache Deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mise.toml', 'mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: mix do deps.get, compile
      - run: mix credo
